"""add columns to tradingprofile and add indicatortable

Revision ID: 06ca3eee9323
Revises: 3d1017eecbdc
Create Date: 2026-03-08 20:40:32.617545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ca3eee9323'
down_revision: Union[str, Sequence[str], None] = '3d1017eecbdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('indicator_type', sa.String(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('is_hard_stop', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['trading_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('positions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_positions_opened_at', 'positions', ['created_at'], unique=False)
    op.create_index('ix_positions_profile_symbol_status', 'positions', ['profile_name', 'symbol', 'status'], unique=False)
    op.add_column('trading_profiles', sa.Column('strategy_type', sa.String(), nullable=True))
    op.add_column('trading_profiles', sa.Column('signal_timeframe', sa.String(), nullable=True))
    op.add_column('trading_profiles', sa.Column('signal_cooldown_seconds', sa.Integer(), nullable=True))
    op.add_column('trading_profiles', sa.Column('min_signal_confidence', sa.Float(), nullable=True))
    op.add_column('trading_profiles', sa.Column('min_volume_ratio', sa.Float(), nullable=True))
    op.add_column('trading_profiles', sa.Column('use_market_regime_filter', sa.Boolean(), nullable=True))
    op.add_column('trading_profiles', sa.Column('use_trend_filter', sa.Boolean(), nullable=True))
    op.add_column('trading_profiles', sa.Column('use_entry_filter', sa.Boolean(), nullable=True))
    op.add_column('trading_profiles', sa.Column('use_atr_filter', sa.Boolean(), nullable=True))
    op.add_column('trading_profiles', sa.Column('trend_timeframe', sa.String(), nullable=True))
    op.add_column('trading_profiles', sa.Column('entry_timeframe', sa.String(), nullable=True))
    op.add_column('trading_profiles', sa.Column('min_indicators_required', sa.Integer(), nullable=True))
    op.add_column('trading_profiles', sa.Column('min_entry_indicators_required', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trading_profiles', 'min_entry_indicators_required')
    op.drop_column('trading_profiles', 'min_indicators_required')
    op.drop_column('trading_profiles', 'entry_timeframe')
    op.drop_column('trading_profiles', 'trend_timeframe')
    op.drop_column('trading_profiles', 'use_atr_filter')
    op.drop_column('trading_profiles', 'use_entry_filter')
    op.drop_column('trading_profiles', 'use_trend_filter')
    op.drop_column('trading_profiles', 'use_market_regime_filter')
    op.drop_column('trading_profiles', 'min_volume_ratio')
    op.drop_column('trading_profiles', 'min_signal_confidence')
    op.drop_column('trading_profiles', 'signal_cooldown_seconds')
    op.drop_column('trading_profiles', 'signal_timeframe')
    op.drop_column('trading_profiles', 'strategy_type')
    op.drop_index('ix_positions_profile_symbol_status', table_name='positions')
    op.drop_index('ix_positions_opened_at', table_name='positions')
    op.alter_column('positions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('indicators')
    # ### end Alembic commands ###
