"""Add trading_type column

Revision ID: 084059a2769b
Revises: 19bb90f164bf
Create Date: 2026-03-21 17:44:03.735703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084059a2769b'
down_revision: Union[str, Sequence[str], None] = '19bb90f164bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_signal_log_profile'), table_name='ai_signal_log')
    op.create_index(op.f('ix_ai_signal_log_outcome_resolved'), 'ai_signal_log', ['outcome_resolved'], unique=False)
    op.create_index(op.f('ix_ai_signal_log_pair'), 'ai_signal_log', ['pair'], unique=False)
    op.create_index(op.f('ix_ai_signal_log_profile_name'), 'ai_signal_log', ['profile_name'], unique=False)
    op.create_index(op.f('ix_ai_signal_log_timestamp'), 'ai_signal_log', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_ai_stats_computed_at'), table_name='ai_vs_rules_stats')
    op.create_index(op.f('ix_ai_vs_rules_stats_computed_at'), 'ai_vs_rules_stats', ['computed_at'], unique=False)
    op.create_index(op.f('ix_ai_vs_rules_stats_pair'), 'ai_vs_rules_stats', ['pair'], unique=False)
    op.alter_column('config_audit_log', 'changed_by',
               existing_type=sa.VARCHAR(length=64),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_config_audit_log_changed_at'), 'config_audit_log', ['changed_at'], unique=False)
    op.add_column('trading_profiles', sa.Column('trading_type', sa.String(), server_default='rules_live', nullable=True))
    # ### end Alembic commands ###
    op.execute("""UPDATE trading_profiles set strategy_type='trend_following', trading_type='ai_live' where id = 1""")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trading_profiles', 'trading_type')
    op.drop_index(op.f('ix_config_audit_log_changed_at'), table_name='config_audit_log')
    op.alter_column('config_audit_log', 'changed_by',
               existing_type=sa.VARCHAR(length=64),
               server_default=sa.text("'web_ui'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_ai_vs_rules_stats_pair'), table_name='ai_vs_rules_stats')
    op.drop_index(op.f('ix_ai_vs_rules_stats_computed_at'), table_name='ai_vs_rules_stats')
    op.create_index(op.f('ix_ai_stats_computed_at'), 'ai_vs_rules_stats', ['computed_at'], unique=False)
    op.drop_index(op.f('ix_ai_signal_log_timestamp'), table_name='ai_signal_log')
    op.drop_index(op.f('ix_ai_signal_log_profile_name'), table_name='ai_signal_log')
    op.drop_index(op.f('ix_ai_signal_log_pair'), table_name='ai_signal_log')
    op.drop_index(op.f('ix_ai_signal_log_outcome_resolved'), table_name='ai_signal_log')
    op.create_index(op.f('ix_ai_signal_log_profile'), 'ai_signal_log', ['profile_name'], unique=False)
    # ### end Alembic commands ###
