"""add_position_max_invalidation_to_profile

Revision ID: 5c3db2ff2ca8
Revises: 084059a2769b
Create Date: 2026-03-23 11:44:29.715828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3db2ff2ca8'
down_revision: Union[str, Sequence[str], None] = '084059a2769b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_profiles', sa.Column('max_position_hours', sa.Integer(), nullable=True))
    op.add_column('trading_profiles', sa.Column('use_trend_invalidation_exit', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('trading_profiles', sa.Column('trend_invalidation_indicators', sa.String(length=24), server_default=sa.text("'entry'"), nullable=False))
    op.add_column('trading_profiles', sa.Column('min_position_age_for_trend_check', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    op.execute("""UPDATE trading_profiles 
                       set max_position_hours=18, 
                           use_trend_invalidation_exit=true, 
                           trend_invalidation_indicators='entry',  
                           min_position_age_for_trend_check = 240
                   where name = 'default'""")
    op.execute("""UPDATE trading_profiles 
                       set max_position_hours=48, 
                           use_trend_invalidation_exit=true, 
                           trend_invalidation_indicators='entry',  
                           min_position_age_for_trend_check = 250
                   where name = 'profile3'""")
    op.execute("""UPDATE trading_profiles 
                       set max_position_hours=2, 
                           use_trend_invalidation_exit=true, 
                           trend_invalidation_indicators='mean_reversion',  
                           min_position_age_for_trend_check = 20
                   where name = '15m_MB_ATR'""")
    op.execute("""UPDATE trading_profiles 
                       set max_position_hours=12, 
                           use_trend_invalidation_exit=true, 
                           trend_invalidation_indicators='entry',  
                           min_position_age_for_trend_check = 45
                   where name = '15m_no_trend'""")
    op.execute("""UPDATE trading_profiles 
                       set max_position_hours=2, 
                           use_trend_invalidation_exit=false, 
                           trend_invalidation_indicators='entry',  
                           min_position_age_for_trend_check = 45
                   where name = '15m_MB'""")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trading_profiles', 'min_position_age_for_trend_check')
    op.drop_column('trading_profiles', 'trend_invalidation_indicators')
    op.drop_column('trading_profiles', 'use_trend_invalidation_exit')
    op.drop_column('trading_profiles', 'max_position_hours')
    # ### end Alembic commands ###
