"""add_accounts above profiles

Revision ID: ca9c81038442
Revises: 5c3db2ff2ca8
Create Date: 2026-03-23 23:27:36.849956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9c81038442'
down_revision: Union[str, Sequence[str], None] = '5c3db2ff2ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('trading_profiles', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_trading_profiles_account_id'), 'trading_profiles', ['account_id'], unique=False)
    op.create_foreign_key(None, 'trading_profiles', 'exchange_accounts', ['account_id'], ['id'], ondelete='SET NULL')

    # 4. Add account_id to circuit_breaker_config (keep profile_name for now)
    op.add_column(
        'circuit_breaker_config',
        sa.Column('account_id', sa.Integer(),
                  sa.ForeignKey('exchange_accounts.id', ondelete='SET NULL'),
                  nullable=True, index=True)
    )

    # 5. Add account_id to daily_balance_snapshots (keep profile_name for now)
    op.add_column(
        'daily_balance_snapshots',
        sa.Column('account_id', sa.Integer(),
                  sa.ForeignKey('exchange_accounts.id', ondelete='SET NULL'),
                  nullable=True, index=True)
    )

    op.add_column(
        'circuit_breaker_events',
        sa.Column('account_id', sa.Integer(),
                  sa.ForeignKey('exchange_accounts.id', ondelete='SET NULL'),
                  nullable=True, index=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_balance_snapshots', 'account_id')
    op.drop_column('circuit_breaker_config', 'account_id')
    op.drop_column('circuit_breaker_events', 'account_id')
    op.drop_constraint(None, 'trading_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_trading_profiles_account_id'), table_name='trading_profiles')
    op.drop_column('trading_profiles', 'account_id')
    op.drop_table('exchange_accounts')
    # ### end Alembic commands ###

