"""add_exchange_type_to_accounts

Revision ID: 5b666302e256
Revises: a1b2c3d4e5f6
Create Date: 2026-04-11 09:27:25.041351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b666302e256'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.add_column(
        'exchange_accounts',
        sa.Column('exchange_type', sa.String(), nullable=False, server_default='backpack')
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_accounts', 'exchange_type')
    # ### end Alembic commands ###
