"""add_wallet_addr_to_exchangeacct

Revision ID: d3444f5ec20e
Revises: 5b666302e256
Create Date: 2026-04-12 16:32:34.163872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3444f5ec20e'
down_revision: Union[str, Sequence[str], None] = '5b666302e256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_accounts', sa.Column('wallet_address', sa.String(), nullable=True))
    op.alter_column('exchange_accounts', 'exchange_type',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchange_accounts', 'exchange_type',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'backpack'::character varying"),
               existing_nullable=False)
    op.drop_column('exchange_accounts', 'wallet_address')
    # ### end Alembic commands ###
