"""remove_api_key_secret_from_trading_profiles

Revision ID: 90d636e1d4bd
Revises: d3444f5ec20e
Create Date: 2026-04-12 21:09:50.489735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d636e1d4bd'
down_revision: Union[str, Sequence[str], None] = 'd3444f5ec20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trading_profiles', 'api_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trading_profiles', 'secret',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trading_profiles', 'secret',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('trading_profiles', 'api_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
