"""add_leverage_multiplier_to_profile

Revision ID: b2e1285a91e8
Revises: 093856e3a812
Create Date: 2026-04-17 16:19:59.463619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e1285a91e8'
down_revision: Union[str, Sequence[str], None] = '093856e3a812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_profiles', sa.Column('leverage_multiplier', sa.Float(), server_default=sa.text('1.0'), nullable=False))
    op.alter_column('trading_profiles', 'enable_signal_generation',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trading_profiles', 'enable_signal_generation',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.drop_column('trading_profiles', 'leverage_multiplier')
    # ### end Alembic commands ###

