"""add maker execution fields

Adds maker-first entry config to trading_profiles and maker/taker attribution to
positions. See docs/maker_execution_plan.md.

All columns are additive and nullable (or have a server default), so applying
this migration does not change any existing row's behaviour: entry_order_mode
defaults to 'taker', which is the unchanged path.

Hand-written (not autogenerated) to avoid pulling in unrelated schema drift.

Revision ID: 19c1389b6275
Revises: 551196a18d59
Create Date: 2026-07-21
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "19c1389b6275"
down_revision: Union[str, Sequence[str], None] = "551196a18d59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "trading_profiles",
        sa.Column("entry_order_mode", sa.String(), nullable=False,
                  server_default=sa.text("'taker'")),
    )
    op.add_column(
        "trading_profiles",
        sa.Column("maker_timeout_sec", sa.Integer(), nullable=True),
    )
    op.add_column(
        "positions",
        sa.Column("fill_type", sa.String(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("positions", "fill_type")
    op.drop_column("trading_profiles", "maker_timeout_sec")
    op.drop_column("trading_profiles", "entry_order_mode")
