"""baseline

Revision ID: 3d1017eecbdc
Revises: 
Create Date: 2026-03-08 20:19:47.045707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d1017eecbdc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_positions_opened_at', 'positions', ['created_at'], unique=False)
    op.create_index('ix_positions_profile_symbol_status', 'positions', ['profile_name', 'symbol', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_positions_profile_symbol_status', table_name='positions')
    op.drop_index('ix_positions_opened_at', table_name='positions')
    op.alter_column('positions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
