"""add price_path_shadow for 1m intra-candle path

Revision ID: 551196a18d59
Revises: 8e0972d01e02
Create Date: 2026-07-20 09:37:24.587639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '551196a18d59'
down_revision: Union[str, Sequence[str], None] = '8e0972d01e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_path_shadow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timestamp', 'source', name='uq_price_path_bar')
    )
    op.create_index('ix_price_path_lookup', 'price_path_shadow', ['symbol', 'timestamp'], unique=False)
    op.create_index(op.f('ix_price_path_shadow_source'), 'price_path_shadow', ['source'], unique=False)
    op.create_index(op.f('ix_price_path_shadow_symbol'), 'price_path_shadow', ['symbol'], unique=False)
    op.create_index(op.f('ix_price_path_shadow_timestamp'), 'price_path_shadow', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the path table. Nothing else here touches live tables."""
    op.drop_index('ix_price_path_lookup', table_name='price_path_shadow')
    op.drop_index(op.f('ix_price_path_shadow_source'), table_name='price_path_shadow')
    op.drop_index(op.f('ix_price_path_shadow_symbol'), table_name='price_path_shadow')
    op.drop_index(op.f('ix_price_path_shadow_timestamp'), table_name='price_path_shadow')
    op.drop_table('price_path_shadow')
