"""add trend_analysis_shadow for candle fetcher parallel run

Revision ID: 8e0972d01e02
Revises: c5f2a8b31e97
Create Date: 2026-07-19 23:11:14.902854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e0972d01e02'
down_revision: Union[str, Sequence[str], None] = 'c5f2a8b31e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_analysis_shadow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('ema20', sa.Float(), nullable=True),
    sa.Column('ema50', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.Column('bb_basis', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('volume_sma', sa.Float(), nullable=True),
    sa.Column('adx', sa.Float(), nullable=True),
    sa.Column('atr_pct', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_symbol', sa.String(), nullable=True),
    sa.Column('is_backfill', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', 'source', name='uq_trend_shadow_bar')
    )
    op.create_index(op.f('ix_trend_analysis_shadow_source'), 'trend_analysis_shadow', ['source'], unique=False)
    op.create_index(op.f('ix_trend_analysis_shadow_symbol'), 'trend_analysis_shadow', ['symbol'], unique=False)
    op.create_index(op.f('ix_trend_analysis_shadow_timeframe'), 'trend_analysis_shadow', ['timeframe'], unique=False)
    op.create_index(op.f('ix_trend_analysis_shadow_timestamp'), 'trend_analysis_shadow', ['timestamp'], unique=False)
    op.create_index('ix_trend_shadow_lookup', 'trend_analysis_shadow', ['symbol', 'timeframe', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the shadow table. Nothing else in this migration touches live tables."""
    op.drop_index('ix_trend_shadow_lookup', table_name='trend_analysis_shadow')
    op.drop_index(op.f('ix_trend_analysis_shadow_timestamp'), table_name='trend_analysis_shadow')
    op.drop_index(op.f('ix_trend_analysis_shadow_timeframe'), table_name='trend_analysis_shadow')
    op.drop_index(op.f('ix_trend_analysis_shadow_symbol'), table_name='trend_analysis_shadow')
    op.drop_index(op.f('ix_trend_analysis_shadow_source'), table_name='trend_analysis_shadow')
    op.drop_table('trend_analysis_shadow')
