"""
backtesting/profile_samples/prod_profiles.py
=============================================
Exact replicas of live production profiles used for prod-vs-backtest comparison.

To add a profile:  paste the exported dict from /profiles/{name}/export-python
                   directly into PROD_PROFILES and add a trailing comma.
To remove a profile: delete its entry from the list.
To change symbols:   edit the "symbols" key inside that dict.

The "display_name" field inside each dict is used as the profile identifier
in all backtest output — no variable names or dict keys needed.
"""

# Exported 5 active profile(s) with signal generation — 2026-07-25 12:22 UTC
PROD_PROFILES = [
# Exported from profile: 15m_MB_ATR
{
    "display_name": "mr_opt_v8_deep_cap_bounceAI",
    "symbols": ['BNB_USDC', 'BTC_USDC', 'ETH_USDC', 'SOL_USDC', 'XRP_USDC', 'ZEC_USDC','DOGE_USDC','SUI_USDC','SEI_USDC'],
    "trading_type": "rules_live",
    "strategy_type": "mean_reversion",
    "market_type": "SPOT",
    "entry_timeframe": "15",
    "trend_timeframe": "60",
    "exit_timeframe": "60",
    "take_profit_pct": 1.0,
    "stop_loss_pct": 0.9,
    "trailing_stop_pct": 0.5,
    "arm_trailing_stop_pct": 0.6,
    "use_trailing_stop": True,
    "enable_signal_generation": True,
    "signal_cooldown_minutes": 20,
    "sl_cooldown_minutes": 20,
    "tp_cooldown_minutes": 20,
    "min_signal_confidence": 66.0,
    "min_volume_ratio": 1.0,
    "use_trend_filter": True,
    "use_entry_filter": True,
    "max_position_hours": 6,
    "use_market_regime_filter": False,
    "regime_timeframe": None,
    "default_order_size_usdc": 100.0,
    "max_position_size_pct": 30.0,
    "max_open_positions": 1,
    "max_open_positions_per_profile": 2,
    "risk_group": None,
    "max_portfolio_exposure_pct": 100.0,
    "leverage_multiplier": 1.0,
    "use_trend_invalidation_exit": True,
    "trend_invalidation_indicators": "trend",
    "min_position_age_for_trend_check": 30,
    "trading_hours": [],
    "trend_indicators": [
        {"type": "rsi_oversold", "params": {"max_value": 35, "require_rising": False, "min_momentum": 0.3}},
        {"type": "adx_regime", "params": {"min_adx": 18, "max_adx": 65}},
    ],
    "min_indicators_required": 2,
    "entry_indicator_groups": {'reversal_confirm': {'hard_stop': True, 'require_all': False}},
    "entry_indicators": [
        {"type": "rsi_reversal_momentum", "params": {"lookback_candles": 12, "oversold_threshold": 25, "current_min": 28, "min_jump": 4, "require_sustained": False, "hard_stop": True}},
        {"type": "volume_spike", "params": {"min_ratio": 1.5, "max_ratio": 8, "hard_stop": True}},
        {"type": "bollinger_bands", "params": {"band": "lower", "mode": "pct_b", "max_pct_b": 0.4}},
        {"type": "rsi_overbought", "params": {"min_value": 45, "hard_stop": True}},
    ],
    "min_entry_indicators_required": 4,
},
# Exported from profile: 15m_no_trend
{
    "display_name": "15m_tf_v9_atrcap070",
    "symbols": ['BTC_USDC', 'ETH_USDC', 'SOL_USDC', 'XRP_USDC', 'ZEC_USDC','DOGE_USDC','SUI_USDC','SEI_USDC'],
    "trading_type": "rules_live",
    "strategy_type": "trend_following",
    "market_type": "SPOT",
    "entry_timeframe": "15",
    "trend_timeframe": "60",
    "exit_timeframe": "15",
    "take_profit_pct": 3.0,
    "stop_loss_pct": 0.8,
    "trailing_stop_pct": 0.25,
    "arm_trailing_stop_pct": 0.35,
    "use_trailing_stop": True,
    "enable_signal_generation": True,
    "signal_cooldown_minutes": 15,
    "sl_cooldown_minutes": 130,
    "tp_cooldown_minutes": 70,
    "min_signal_confidence": 70.0,
    "min_volume_ratio": 1.0,
    "use_trend_filter": True,
    "use_entry_filter": True,
    "max_position_hours": 12,
    "use_market_regime_filter": True,
    "regime_timeframe": "60",
    "default_order_size_usdc": 100.0,
    "max_position_size_pct": 40.0,
    "max_open_positions": 1,
    "max_open_positions_per_profile": 2,
    "risk_group": "15m_longs",
    "max_portfolio_exposure_pct": 100.0,
    "leverage_multiplier": 1.0,
    "use_trend_invalidation_exit": True,
    "trend_invalidation_indicators": "trend",
    "min_position_age_for_trend_check": 15,
    "trading_hours": [
        {"day_of_week": 0, "start_time": "05:00", "end_time": "12:00", "enabled": True},
        {"day_of_week": 0, "start_time": "15:00", "end_time": "21:00", "enabled": True},
        {"day_of_week": 1, "start_time": "02:00", "end_time": "23:00", "enabled": True},
        {"day_of_week": 2, "start_time": "01:00", "end_time": "12:00", "enabled": True},
        {"day_of_week": 2, "start_time": "14:00", "end_time": "23:00", "enabled": True},
        {"day_of_week": 3, "start_time": "03:00", "end_time": "12:00", "enabled": True},
        {"day_of_week": 3, "start_time": "14:00", "end_time": "21:00", "enabled": True},
        {"day_of_week": 4, "start_time": "03:00", "end_time": "12:00", "enabled": True},
        {"day_of_week": 4, "start_time": "14:00", "end_time": "21:00", "enabled": True},
    ],
    "trend_indicators": [
        {"type": "ema_cross", "params": {}},
        {"type": "adx_regime", "params": {"min_adx": 30, "max_adx": 65, "hard_stop": True}},
        {"type": "ema_slope", "params": {"ema": 20, "direction": "rising", "min_slope_pct": 0.025, "hard_stop": True}},
        {"type": "ema_gap", "params": {"max_gap_pct": 1.5, "mode": "max", "hard_stop": True}},
        {"type": "rsi_range", "params": {"min": 54, "max": 68, "invert": True, "hard_stop": True}},
    ],
    "min_indicators_required": 5,
    "entry_indicators": [
        {"type": "rsi_threshold", "params": {"period": 14, "min_value": 55, "use_momentum": True, "early_threshold": 50, "hard_stop": True}},
        {"type": "rsi_momentum", "params": {"min_momentum": 1, "max_momentum": 8, "lookback_candles": 1}},
        {"type": "ema_slope", "params": {"ema": 20, "direction": "rising", "min_slope_pct": 0.03, "hard_stop": True}},
        {"type": "rsi_overbought", "params": {"side": "long", "min_value": 72, "max_value": 100, "hard_stop": True}},
        {"type": "volume_spike", "params": {"min_ratio": 1.5, "max_ratio": 10, "hard_stop": True}},
        {"type": "price_vs_ema", "params": {"ema": 20, "min_gap_pct": -0.3, "max_gap_pct": 1.5}},
        {"type": "price_vs_vwap", "params": {}},
        {"type": "ema_cross", "params": {"use_slope": False, "min_slope_pct": 0.01, "hard_stop": True}},
        {"type": "atr_regime", "params": {"max_pct": 0.7, "period": 14, "hard_stop": True}},
    ],
    "min_entry_indicators_required": 7,
},
# Exported from profile: 4h_v19_tight_pullback
{
    "display_name": "4hr_p3_v11_slope_relaxedAI",
    "symbols": ['BNB_USDC', 'BTC_USDC', 'ETH_USDC', 'SOL_USDC', 'XRP_USDC', 'ZEC_USDC','DOGE_USDC','SUI_USDC','SEI_USDC'],
    "trading_type": "rules_live",
    "strategy_type": "trend_following",
    "market_type": "SPOT",
    "entry_timeframe": "60",
    "trend_timeframe": "240",
    "exit_timeframe": None,
    "take_profit_pct": 3.5,
    "stop_loss_pct": 2.0,
    "trailing_stop_pct": 0.6,
    "arm_trailing_stop_pct": 1.5,
    "use_trailing_stop": True,
    "enable_signal_generation": True,
    "signal_cooldown_minutes": 241,
    "sl_cooldown_minutes": 490,
    "tp_cooldown_minutes": 250,
    "min_signal_confidence": 74.0,
    "min_volume_ratio": 1.0,
    "use_trend_filter": True,
    "use_entry_filter": True,
    "max_position_hours": 72,
    "use_market_regime_filter": False,
    "regime_timeframe": None,
    "default_order_size_usdc": 100.0,
    "max_position_size_pct": 40.0,
    "max_open_positions": 1,
    "max_open_positions_per_profile": 2,
    "risk_group": "4hr_longs",
    "max_portfolio_exposure_pct": 100.0,
    "leverage_multiplier": 1.0,
    "use_trend_invalidation_exit": True,
    "trend_invalidation_indicators": "trend",
    "min_position_age_for_trend_check": 30,
    "trading_hours": [],
    "trend_indicator_groups": {'extension_check': {'hard_stop': True, 'require_all': False}},
    "trend_indicators": [
        {"type": "ema_cross", "params": {"hard_stop": True}},
        {"type": "ema_slope", "params": {"ema": 20, "direction": "rising", "min_slope_pct": 0.02, "hard_stop": True}},
        {"type": "rsi_range", "params": {"min": 52, "max": 63, "invert": True, "hard_stop": True}},
    ],
    "min_indicators_required": 3,
    "entry_indicators": [
        {"type": "adx_regime", "params": {"min_adx": 22, "max_adx": 40}},
        {"type": "rsi_range", "params": {"min": 30, "max": 50, "invert": True, "hard_stop": True}},
        {"type": "volume_spike", "params": {"min_ratio": 1.2, "max_ratio": 8}},
    ],
    "min_entry_indicators_required": 3,
},
# Exported from profile: 4hr_ema50drop
{
    "display_name": "4hr_p3_v7_rsi_pullbackAI",
    "symbols": ['BNB_USDC', 'BTC_USDC', 'ETH_USDC', 'SOL_USDC', 'XRP_USDC', 'ZEC_USDC','DOGE_USDC','SUI_USDC','SEI_USDC'],
    "trading_type": "rules_live",
    "strategy_type": "trend_following",
    "market_type": "SPOT",
    "entry_timeframe": "60",
    "trend_timeframe": "240",
    "exit_timeframe": "240",
    "take_profit_pct": 3.0,
    "stop_loss_pct": 2.0,
    "trailing_stop_pct": 1.0,
    "arm_trailing_stop_pct": 1.5,
    "use_trailing_stop": True,
    "enable_signal_generation": True,
    "signal_cooldown_minutes": 241,
    "sl_cooldown_minutes": 485,
    "tp_cooldown_minutes": 241,
    "min_signal_confidence": 74.0,
    "min_volume_ratio": 1.0,
    "use_trend_filter": True,
    "use_entry_filter": True,
    "max_position_hours": 72,
    "use_market_regime_filter": False,
    "regime_timeframe": None,
    "default_order_size_usdc": 200.0,
    "max_position_size_pct": 40.0,
    "max_open_positions": 1,
    "max_open_positions_per_profile": 2,
    "risk_group": "4hr_longs",
    "max_portfolio_exposure_pct": 80.0,
    "leverage_multiplier": 1.0,
    "use_trend_invalidation_exit": True,
    "trend_invalidation_indicators": "trend",
    "min_position_age_for_trend_check": 241,
    "trading_hours": [],
    "trend_indicators": [
        {"type": "ema_cross", "params": {"hard_stop": True}},
        {"type": "rsi_range", "params": {"min": 52, "max": 63, "invert": True, "hard_stop": True}},
    ],
    "min_indicators_required": 2,
    "entry_indicators": [
        {"type": "adx_regime", "params": {"min_adx": 22, "max_adx": 40}},
        {"type": "rsi_range", "params": {"min": 30, "max": 50, "invert": True, "hard_stop": True}},
    ],
    "min_entry_indicators_required": 2,
},
# Exported from profile: spike_entry
{
    "display_name": "mr_opt_v7_adx_rsi_turn_wideAI",
    "symbols": ['BNB_USDC', 'BTC_USDC', 'ETH_USDC', 'SOL_USDC', 'XRP_USDC', 'ZEC_USDC','DOGE_USDC','SUI_USDC','SEI_USDC'],
    "trading_type": "rules_live",
    "strategy_type": "mean_reversion",
    "market_type": "SPOT",
    "entry_timeframe": "15",
    "trend_timeframe": "60",
    "exit_timeframe": "60",
    "take_profit_pct": 2.2,
    "stop_loss_pct": 0.8,
    "trailing_stop_pct": 0.5,
    "arm_trailing_stop_pct": 1.2,
    "use_trailing_stop": True,
    "enable_signal_generation": True,
    "signal_cooldown_minutes": 18,
    "sl_cooldown_minutes": 15,
    "tp_cooldown_minutes": 15,
    "min_signal_confidence": 65.0,
    "min_volume_ratio": 1.0,
    "use_trend_filter": True,
    "use_entry_filter": True,
    "max_position_hours": 6,
    "use_market_regime_filter": False,
    "regime_timeframe": None,
    "default_order_size_usdc": 200.0,
    "max_position_size_pct": 40.0,
    "max_open_positions": 1,
    "max_open_positions_per_profile": 2,
    "risk_group": None,
    "max_portfolio_exposure_pct": 80.0,
    "leverage_multiplier": 1.0,
    "use_trend_invalidation_exit": True,
    "trend_invalidation_indicators": "trend",
    "min_position_age_for_trend_check": 15,
    "trading_hours": [],
    "trend_indicators": [
        {"type": "rsi_oversold", "params": {"max_value": 38, "require_rising": True, "min_momentum": 0.3}},
        {"type": "adx_regime", "params": {"min_adx": 18, "max_adx": 65}},
    ],
    "min_indicators_required": 2,
    "entry_indicators": [
        {"type": "rsi_reversal_momentum", "params": {"lookback_candles": 8, "oversold_threshold": 30, "current_min": 30, "min_jump": 3, "require_sustained": False, "sustained_rise_mode": "net", "hard_stop": True}},
        {"type": "price_below_vwap", "params": {"min_gap_pct": -0.5, "max_gap_pct": -10}},
        {"type": "bollinger_bands", "params": {"band": "lower", "mode": "pct_b", "max_pct_b": 0.3}},
        {"type": "rsi_overbought", "params": {"min_value": 40}},
        {"type": "volume_spike", "params": {"min_ratio": 1, "max_ratio": 8}},
    ],
    "min_entry_indicators_required": 4,
},
]
