"""
backtesting/profile_samples/prod_profiles.py
=============================================
Exact replicas of live production profiles used for prod-vs-backtest comparison.

To add a profile:  paste the exported dict from /profiles/{name}/export-python
                   directly into PROD_PROFILES and add a trailing comma.
To remove a profile: delete its entry from the list.
To change symbols:   edit the "symbols" key inside that dict.

The "display_name" field inside each dict is used as the profile identifier
in all backtest output — no variable names or dict keys needed.
"""

# Exported 4 active profile(s) with signal generation — 2026-08-05 22:59 UTC
# Exported 4 active profile(s) with signal generation — 2026-08-18 13:08 UTC
PROD_PROFILES = [
# Exported from profile: profile1
{
    "display_name": "15m_tf_v90_atrcap070_seidoge",
    "symbols": ['DOGE_USDC', 'SEI_USDC'],
    "trading_type": "rules_live",
    "strategy_type": "trend_following",
    "market_type": "SPOT",
    "entry_timeframe": "15",
    "trend_timeframe": "60",
    "exit_timeframe": "60",
    "take_profit_pct": 3.0,
    "stop_loss_pct": 0.8,
    "trailing_stop_pct": 0.25,
    "arm_trailing_stop_pct": 0.35,
    "use_trailing_stop": True,
    "enable_signal_generation": True,
    "signal_cooldown_minutes": 15,
    "sl_cooldown_minutes": 130,
    "tp_cooldown_minutes": 70,
    "min_signal_confidence": 70.0,
    "min_volume_ratio": 1.0,
    "use_trend_filter": True,
    "use_entry_filter": True,
    "max_position_hours": 18,
    "use_market_regime_filter": True,
    "regime_timeframe": "60",
    "default_order_size_usdc": 100.0,
    "max_position_size_pct": 40.0,
    "max_open_positions": 1,
    "max_open_positions_per_profile": 2,
    "risk_group": "15m_longs",
    "max_portfolio_exposure_pct": 100.0,
    "leverage_multiplier": 1.0,
    "use_trend_invalidation_exit": True,
    "trend_invalidation_indicators": "trend",
    "min_position_age_for_trend_check": 15,
    "trading_hours": [
        {"day_of_week": 0, "start_time": "05:00", "end_time": "12:00", "enabled": True},
        {"day_of_week": 0, "start_time": "15:00", "end_time": "21:00", "enabled": True},
        {"day_of_week": 1, "start_time": "02:00", "end_time": "23:00", "enabled": True},
        {"day_of_week": 2, "start_time": "01:00", "end_time": "12:00", "enabled": True},
        {"day_of_week": 2, "start_time": "14:00", "end_time": "23:00", "enabled": True},
        {"day_of_week": 3, "start_time": "03:00", "end_time": "12:00", "enabled": True},
        {"day_of_week": 3, "start_time": "14:00", "end_time": "21:00", "enabled": True},
        {"day_of_week": 4, "start_time": "03:00", "end_time": "12:00", "enabled": True},
        {"day_of_week": 4, "start_time": "14:00", "end_time": "21:00", "enabled": True},
    ],
    "trend_indicators": [
        {"type": "ema_slope", "params": {"ema": 20, "direction": "rising", "min_slope_pct": 0.025, "hard_stop": True}},
        {"type": "rsi_range", "params": {"min": 54, "max": 68, "invert": True, "hard_stop": True}},
        {"type": "ema_gap", "params": {"max_gap_pct": 1.5, "mode": "max", "hard_stop": True}},
        {"type": "ema_cross", "params": {}},
        {"type": "adx_regime", "params": {"min_adx": 30, "max_adx": 65, "hard_stop": True}},
    ],
    "min_indicators_required": 5,
    "entry_indicators": [
        {"type": "atr_regime", "params": {"max_pct": 0.7, "period": 14, "hard_stop": True}},
        {"type": "rsi_overbought", "params": {"side": "long", "min_value": 72, "max_value": 100, "hard_stop": True}},
        {"type": "rsi_threshold", "params": {"period": 14, "min_value": 55, "use_momentum": True, "early_threshold": 50, "hard_stop": True}},
        {"type": "rsi_momentum", "params": {"min_momentum": 1, "max_momentum": 8, "lookback_candles": 1}},
        {"type": "ema_slope", "params": {"ema": 20, "direction": "rising", "min_slope_pct": 0.03, "hard_stop": True}},
        {"type": "volume_spike", "params": {"min_ratio": 1.5, "max_ratio": 10, "hard_stop": True}},
        {"type": "price_vs_vwap", "params": {}},
        {"type": "price_vs_ema", "params": {"ema": 20, "min_gap_pct": -0.3, "max_gap_pct": 1.5}},
        {"type": "ema_cross", "params": {"use_slope": False, "min_slope_pct": 0.01, "hard_stop": True}},
    ],
    "min_entry_indicators_required": 7,
},
# Exported from profile: profile10
{
    "display_name": "4hr_dip_v7_deep_dip_satellite",
    "symbols": ['BNB_USDC', 'BTC_USDC', 'ETH_USDC', 'SEI_USDC', 'SOL_USDC', 'SUI_USDC', 'XRP_USDC', 'ZEC_USDC'],
    "trading_type": "rules_live",
    "strategy_type": "mean_reversion",
    "market_type": "SPOT",
    "entry_timeframe": "240",
    "trend_timeframe": "1D",
    "exit_timeframe": "240",
    "take_profit_pct": 99.0,
    "stop_loss_pct": 99.0,
    "trailing_stop_pct": 0.6,
    "arm_trailing_stop_pct": 3.5,
    "use_trailing_stop": True,
    "enable_signal_generation": True,
    "signal_cooldown_minutes": 1300,
    "sl_cooldown_minutes": 490,
    "tp_cooldown_minutes": 250,
    "min_signal_confidence": 60.0,
    "min_volume_ratio": 1.0,
    "use_trend_filter": True,
    "use_entry_filter": True,
    "max_position_hours": 720,
    "use_market_regime_filter": False,
    "regime_timeframe": None,
    "default_order_size_usdc": 100.0,
    "max_position_size_pct": 40.0,
    "max_open_positions": 1,
    "max_open_positions_per_profile": 20,
    "risk_group": "4hr_longs",
    "max_portfolio_exposure_pct": 100.0,
    "leverage_multiplier": 1.0,
    "use_trend_invalidation_exit": True,
    "trend_invalidation_indicators": "exit",
    "min_position_age_for_trend_check": 30,
    "trading_hours": [],
    "trend_indicator_groups": {'extension_check': {'hard_stop': True, 'require_all': False}},
    "trend_indicators": [
        {"type": "price_vs_ema", "params": {"ema": 50, "min_gap_pct": 0, "hard_stop": True}},
    ],
    "min_indicators_required": 1,
    "entry_indicators": [
        {"type": "distance_from_high", "params": {"lookback_bars": 18, "min_pct_below": 12, "max_pct_below": 30, "hard_stop": True}},
        {"type": "rsi_overbought", "params": {"side": "long", "min_value": 45, "hard_stop": True}},
    ],
    "min_entry_indicators_required": 2,
    "exit_indicators": [
        {"type": "rsi_overbought", "params": {"side": "long", "min_value": 59, "max_value": 30, "lookback_candles": None}},
        {"type": "price_extended_below_ema", "params": {"ema": 20, "min_gap_pct": -0.001, "max_gap_pct": -99}},
    ],
    "min_exit_indicators_required": 1,
},
# Exported from profile: profile4
{
    "display_name": "15m_tf_v9_atrcap070",
    "symbols": ['BNB_USDC', 'BTC_USDC', 'ETH_USDC', 'SOL_USDC', 'SUI_USDC', 'XRP_USDC', 'ZEC_USDC'],
    "trading_type": "rules_live",
    "strategy_type": "trend_following",
    "market_type": "SPOT",
    "entry_timeframe": "15",
    "trend_timeframe": "60",
    "exit_timeframe": "60",
    "take_profit_pct": 3.0,
    "stop_loss_pct": 0.8,
    "trailing_stop_pct": 0.25,
    "arm_trailing_stop_pct": 0.35,
    "use_trailing_stop": True,
    "enable_signal_generation": True,
    "signal_cooldown_minutes": 15,
    "sl_cooldown_minutes": 130,
    "tp_cooldown_minutes": 70,
    "min_signal_confidence": 70.0,
    "min_volume_ratio": 1.0,
    "use_trend_filter": True,
    "use_entry_filter": True,
    "max_position_hours": 12,
    "use_market_regime_filter": True,
    "regime_timeframe": "60",
    "default_order_size_usdc": 100.0,
    "max_position_size_pct": 40.0,
    "max_open_positions": 1,
    "max_open_positions_per_profile": 2,
    "risk_group": "15m_longs",
    "max_portfolio_exposure_pct": 100.0,
    "leverage_multiplier": 1.0,
    "use_trend_invalidation_exit": True,
    "trend_invalidation_indicators": "trend",
    "min_position_age_for_trend_check": 60,
    "trading_hours": [],
    "trend_indicators": [
        {"type": "ema_cross", "params": {}},
        {"type": "adx_regime", "params": {"min_adx": 30, "max_adx": 65, "hard_stop": True}},
        {"type": "ema_slope", "params": {"ema": 20, "direction": "rising", "min_slope_pct": 0.025, "hard_stop": True}},
        {"type": "ema_gap", "params": {"max_gap_pct": 1.5, "mode": "max", "hard_stop": True}},
        {"type": "rsi_range", "params": {"min": 54, "max": 68, "invert": True, "hard_stop": True}},
    ],
    "min_indicators_required": 5,
    "entry_indicators": [
        {"type": "rsi_threshold", "params": {"period": 14, "min_value": 55, "use_momentum": True, "early_threshold": 50, "hard_stop": True}},
        {"type": "rsi_momentum", "params": {"min_momentum": 1, "max_momentum": 8, "lookback_candles": 1}},
        {"type": "ema_slope", "params": {"ema": 20, "direction": "rising", "min_slope_pct": 0.03, "hard_stop": True}},
        {"type": "rsi_overbought", "params": {"side": "long", "min_value": 72, "max_value": 100, "hard_stop": True}},
        {"type": "volume_spike", "params": {"min_ratio": 1.5, "max_ratio": 10, "hard_stop": True}},
        {"type": "price_vs_ema", "params": {"ema": 20, "min_gap_pct": -0.3, "max_gap_pct": 1.5}},
        {"type": "price_vs_vwap", "params": {}},
        {"type": "ema_cross", "params": {"use_slope": False, "min_slope_pct": 0.01, "hard_stop": True}},
        {"type": "atr_regime", "params": {"max_pct": 0.7, "period": 14, "hard_stop": True}},
    ],
    "min_entry_indicators_required": 7,
},
# Exported from profile: profile7
{
    "display_name": "4hr_dip_v5_rsi_reversal_trail",
    "symbols": ['BNB_USDC', 'BTC_USDC', 'DOGE_USDC', 'ETH_USDC', 'SEI_USDC', 'SOL_USDC', 'SUI_USDC', 'XRP_USDC', 'ZEC_USDC'],
    "trading_type": "rules_live",
    "strategy_type": "mean_reversion",
    "market_type": "SPOT",
    "entry_timeframe": "240",
    "trend_timeframe": "1D",
    "exit_timeframe": "240",
    "take_profit_pct": 99.0,
    "stop_loss_pct": 99.0,
    "trailing_stop_pct": 0.6,
    "arm_trailing_stop_pct": 3.5,
    "use_trailing_stop": True,
    "enable_signal_generation": True,
    "signal_cooldown_minutes": 1300,
    "sl_cooldown_minutes": 485,
    "tp_cooldown_minutes": 241,
    "min_signal_confidence": 60.0,
    "min_volume_ratio": 1.0,
    "use_trend_filter": True,
    "use_entry_filter": True,
    "max_position_hours": 720,
    "use_market_regime_filter": False,
    "regime_timeframe": None,
    "default_order_size_usdc": 200.0,
    "max_position_size_pct": 40.0,
    "max_open_positions": 4,
    "max_open_positions_per_profile": 20,
    "risk_group": "4hr_longs",
    "max_portfolio_exposure_pct": 80.0,
    "leverage_multiplier": 1.0,
    "use_trend_invalidation_exit": True,
    "trend_invalidation_indicators": "exit",
    "min_position_age_for_trend_check": 0,
    "trading_hours": [],
    "trend_indicators": [
        {"type": "price_vs_ema", "params": {"ema": 50, "min_gap_pct": 0, "hard_stop": True}},
    ],
    "min_indicators_required": 1,
    "entry_indicators": [
        {"type": "rsi_reversal_momentum", "params": {"lookback_candles": 4, "oversold_threshold": 35, "current_min": 35, "min_jump": 6, "require_sustained": False, "sustained_rise_mode": "net", "hard_stop": True}},
        {"type": "price_extended_below_ema", "params": {"ema": 20, "min_gap_pct": -0.001, "max_gap_pct": -50, "hard_stop": True}},
    ],
    "min_entry_indicators_required": 2,
    "exit_indicators": [
        {"type": "rsi_overbought", "params": {"side": "long", "min_value": 55}},
        {"type": "price_extended_below_ema", "params": {"ema": 20, "min_gap_pct": -0.001, "max_gap_pct": -99}},
    ],
    "min_exit_indicators_required": 1,
},
]