"""
backtesting/profile_samples/prod_profiles.py
=============================================
Exact replicas of live production profiles used for prod-vs-backtest comparison.

To add a profile:  paste the exported dict from /profiles/{name}/export-python
                   directly into PROD_PROFILES and add a trailing comma.
To remove a profile: delete its entry from the list.
To change symbols:   edit the "symbols" key inside that dict.

The "display_name" field inside each dict is used as the profile identifier
in all backtest output — no variable names or dict keys needed.
"""

# Exported 10 active profile(s) with signal generation — 2026-07-03 11:29 UTC

# Exported 8 active profile(s) with signal generation — 2026-07-15 12:48 UTC
PROD_PROFILES = [
# Exported from profile: 15m_MB_ATR
{
    "display_name": "mr_opt_v8_deep_cap_bounceAI",
    "symbols": ['BNB_USDC', 'BTC_USDC', 'ETH_USDC', 'SOL_USDC', 'XRP_USDC', 'ZEC_USDC'],
    "trading_type": "rules_live",
    "strategy_type": "mean_reversion",
    "market_type": "SPOT",
    "entry_timeframe": "15",
    "trend_timeframe": "60",
    "exit_timeframe": "60",
    "take_profit_pct": 1.0,
    "stop_loss_pct": 0.9,
    "trailing_stop_pct": 0.5,
    "arm_trailing_stop_pct": 0.6,
    "use_trailing_stop": True,
    "enable_signal_generation": True,
    "signal_cooldown_minutes": 20,
    "sl_cooldown_minutes": 20,
    "tp_cooldown_minutes": 20,
    "min_signal_confidence": 66.0,
    "min_volume_ratio": 1.0,
    "use_trend_filter": True,
    "use_entry_filter": True,
    "use_atr_filter": False,
    "max_position_hours": 6,
    "use_market_regime_filter": False,
    "regime_timeframe": None,
    "default_order_size_usdc": 100.0,
    "max_position_size_pct": 30.0,
    "max_open_positions": 1,
    "max_open_positions_per_profile": 2,
    "max_portfolio_exposure_pct": 100.0,
    "leverage_multiplier": 1.0,
    "use_trend_invalidation_exit": True,
    "trend_invalidation_indicators": "trend",
    "min_position_age_for_trend_check": 30,
    "trading_hours": [],
    "trend_indicators": [
        {"type": "rsi_oversold", "params": {"max_value": 35, "require_rising": False, "min_momentum": 0.3}},
        {"type": "adx_regime", "params": {"min_adx": 18, "max_adx": 65}},
    ],
    "min_indicators_required": 2,
    "entry_indicator_groups": {'reversal_confirm': {'hard_stop': True, 'require_all': False}},
    "entry_indicators": [
        {"type": "rsi_reversal_momentum", "params": {"lookback_candles": 12, "oversold_threshold": 25, "current_min": 28, "min_jump": 4, "require_sustained": False, "hard_stop": True}},
        {"type": "volume_spike", "params": {"min_ratio": 1.5, "max_ratio": 8, "hard_stop": True}},
        {"type": "bollinger_bands", "params": {"band": "lower", "mode": "pct_b", "max_pct_b": 0.4}},
        {"type": "rsi_overbought", "params": {"min_value": 45, "hard_stop": True}},
    ],
    "min_entry_indicators_required": 4,
},
# Exported from profile: 15m_no_trend
{
    "display_name": "15m_tf_v4_zone3855_tp9AI",
    "symbols": ['BNB_USDC', 'BTC_USDC', 'ETH_USDC', 'HYPE_USDC', 'SOL_USDC', 'XRP_USDC', 'ZEC_USDC'],
    "trading_type": "rules_live",
    "strategy_type": "trend_following",
    "market_type": "SPOT",
    "entry_timeframe": "15",
    "trend_timeframe": "60",
    "exit_timeframe": "15",
    "take_profit_pct": 0.9,
    "stop_loss_pct": 0.6,
    "trailing_stop_pct": 0.35,
    "arm_trailing_stop_pct": 0.45,
    "use_trailing_stop": True,
    "enable_signal_generation": True,
    "signal_cooldown_minutes": 20,
    "sl_cooldown_minutes": 130,
    "tp_cooldown_minutes": 70,
    "min_signal_confidence": 70.0,
    "min_volume_ratio": 1.1,
    "use_trend_filter": True,
    "use_entry_filter": True,
    "use_atr_filter": False,
    "max_position_hours": 12,
    "use_market_regime_filter": True,
    "regime_timeframe": "240",
    "default_order_size_usdc": 100.0,
    "max_position_size_pct": 40.0,
    "max_open_positions": 1,
    "max_open_positions_per_profile": 2,
    "max_portfolio_exposure_pct": 100.0,
    "leverage_multiplier": 1.0,
    "use_trend_invalidation_exit": True,
    "trend_invalidation_indicators": "exit",
    "min_position_age_for_trend_check": 15,
    "trading_hours": [
        {"day_of_week": 0, "start_time": "05:00", "end_time": "12:00", "enabled": True},
        {"day_of_week": 0, "start_time": "15:00", "end_time": "21:00", "enabled": True},
        {"day_of_week": 1, "start_time": "02:00", "end_time": "23:00", "enabled": True},
        {"day_of_week": 2, "start_time": "01:00", "end_time": "12:00", "enabled": True},
        {"day_of_week": 2, "start_time": "14:00", "end_time": "23:00", "enabled": True},
        {"day_of_week": 3, "start_time": "03:00", "end_time": "12:00", "enabled": True},
        {"day_of_week": 3, "start_time": "14:00", "end_time": "21:00", "enabled": True},
        {"day_of_week": 4, "start_time": "03:00", "end_time": "12:00", "enabled": True},
        {"day_of_week": 4, "start_time": "14:00", "end_time": "21:00", "enabled": True},
    ],
    "trend_indicators": [
        {"type": "ema_cross", "params": {}},
        {"type": "adx_regime", "params": {"min_adx": 22, "max_adx": 65, "hard_stop": True}},
        {"type": "rsi_overbought", "params": {"min_value": 60, "lookback_candles": 5, "hard_stop": True}},
    ],
    "min_indicators_required": 3,
    "entry_indicators": [
        {"type": "rsi_range", "params": {"min": 38, "max": 55, "invert": True}},
        {"type": "rsi_reversal_momentum", "params": {"lookback_candles": 6, "oversold_threshold": 45, "current_min": 44, "min_jump": 5, "require_sustained": True, "hard_stop": True}},
        {"type": "ema_slope", "params": {"ema": 20, "direction": "rising", "min_slope_pct": 0.01, "hard_stop": True}},
    ],
    "min_entry_indicators_required": 3,
    "exit_indicators": [
        {"type": "rsi_overbought", "params": {"min_value": 68, "hard_stop": True}},
        {"type": "ema_slope", "params": {"ema": 20, "direction": "rising", "min_slope_pct": -0.02, "hard_stop": True}},
        {"type": "rsi_threshold", "params": {"period": 14, "min_value": 44, "use_momentum": False}},
    ],
    "min_exit_indicators_required": 1,
},
# Exported from profile: 4h_v19_tight_pullback
{
    "display_name": "4hr_p3_v11_slope_relaxedAI",
    "symbols": ['BNB_USDC', 'BTC_USDC', 'ETH_USDC', 'SOL_USDC', 'XRP_USDC', 'ZEC_USDC'],
    "trading_type": "rules_live",
    "strategy_type": "trend_following",
    "market_type": "SPOT",
    "entry_timeframe": "60",
    "trend_timeframe": "240",
    "exit_timeframe": None,
    "take_profit_pct": 3.5,
    "stop_loss_pct": 2.0,
    "trailing_stop_pct": 0.6,
    "arm_trailing_stop_pct": 1.5,
    "use_trailing_stop": True,
    "enable_signal_generation": True,
    "signal_cooldown_minutes": 241,
    "sl_cooldown_minutes": 490,
    "tp_cooldown_minutes": 250,
    "min_signal_confidence": 74.0,
    "min_volume_ratio": 1.0,
    "use_trend_filter": True,
    "use_entry_filter": True,
    "use_atr_filter": False,
    "max_position_hours": 72,
    "use_market_regime_filter": False,
    "regime_timeframe": None,
    "default_order_size_usdc": 100.0,
    "max_position_size_pct": 40.0,
    "max_open_positions": 1,
    "max_open_positions_per_profile": 2,
    "max_portfolio_exposure_pct": 100.0,
    "leverage_multiplier": 1.0,
    "use_trend_invalidation_exit": True,
    "trend_invalidation_indicators": "trend",
    "min_position_age_for_trend_check": 30,
    "trading_hours": [],
    "trend_indicator_groups": {'extension_check': {'hard_stop': True, 'require_all': False}},
    "trend_indicators": [
        {"type": "ema_cross", "params": {"hard_stop": True}},
        {"type": "ema_slope", "params": {"ema": 20, "direction": "rising", "min_slope_pct": 0.02, "hard_stop": True}},
        {"type": "rsi_range", "params": {"min": 52, "max": 63, "invert": True, "hard_stop": True}},
    ],
    "min_indicators_required": 3,
    "entry_indicators": [
        {"type": "adx_regime", "params": {"min_adx": 22, "max_adx": 40}},
        {"type": "rsi_range", "params": {"min": 30, "max": 50, "invert": True, "hard_stop": True}},
        {"type": "volume_spike", "params": {"min_ratio": 1.2, "max_ratio": 8}},
    ],
    "min_entry_indicators_required": 3,
},
# Exported from profile: 4hr_ema50drop
{
    "display_name": "4hr_p3_v7_rsi_pullbackAI",
    "symbols": ['BNB_USDC', 'BTC_USDC', 'ETH_USDC', 'SOL_USDC', 'XRP_USDC', 'ZEC_USDC'],
    "trading_type": "rules_live",
    "strategy_type": "trend_following",
    "market_type": "SPOT",
    "entry_timeframe": "60",
    "trend_timeframe": "240",
    "exit_timeframe": "240",
    "take_profit_pct": 3.0,
    "stop_loss_pct": 2.0,
    "trailing_stop_pct": 1.0,
    "arm_trailing_stop_pct": 1.5,
    "use_trailing_stop": True,
    "enable_signal_generation": True,
    "signal_cooldown_minutes": 241,
    "sl_cooldown_minutes": 485,
    "tp_cooldown_minutes": 241,
    "min_signal_confidence": 74.0,
    "min_volume_ratio": 1.0,
    "use_trend_filter": True,
    "use_entry_filter": True,
    "use_atr_filter": False,
    "max_position_hours": 72,
    "use_market_regime_filter": False,
    "regime_timeframe": None,
    "default_order_size_usdc": 200.0,
    "max_position_size_pct": 40.0,
    "max_open_positions": 1,
    "max_open_positions_per_profile": 2,
    "max_portfolio_exposure_pct": 80.0,
    "leverage_multiplier": 1.0,
    "use_trend_invalidation_exit": True,
    "trend_invalidation_indicators": "trend",
    "min_position_age_for_trend_check": 241,
    "trading_hours": [],
    "trend_indicators": [
        {"type": "ema_cross", "params": {"hard_stop": True}},
        {"type": "rsi_range", "params": {"min": 52, "max": 63, "invert": True, "hard_stop": True}},
    ],
    "min_indicators_required": 2,
    "entry_indicators": [
        {"type": "adx_regime", "params": {"min_adx": 22, "max_adx": 40}},
        {"type": "rsi_range", "params": {"min": 30, "max": 50, "invert": True, "hard_stop": True}},
    ],
    "min_entry_indicators_required": 2,
},
# Exported from profile: bullet_shorts
{
    "display_name": "bullet_shorts_v15AI",
    "symbols": ['BTC_USDC', 'ETH_USDC', 'SOL_USDC', 'XRP_USDC', 'ZEC_USDC'],
    "trading_type": "rules_live",
    "strategy_type": "short_mean_reversion",
    "market_type": "PERP",
    "entry_timeframe": "15",
    "trend_timeframe": "60",
    "exit_timeframe": "60",
    "take_profit_pct": 1.2,
    "stop_loss_pct": 0.9,
    "trailing_stop_pct": 0.6,
    "arm_trailing_stop_pct": 0.6,
    "use_trailing_stop": True,
    "enable_signal_generation": True,
    "signal_cooldown_minutes": 20,
    "sl_cooldown_minutes": 120,
    "tp_cooldown_minutes": 90,
    "min_signal_confidence": 72.0,
    "min_volume_ratio": 1.0,
    "use_trend_filter": True,
    "use_entry_filter": True,
    "use_atr_filter": False,
    "max_position_hours": 4,
    "use_market_regime_filter": True,
    "regime_timeframe": "240",
    "default_order_size_usdc": 100.0,
    "max_position_size_pct": 40.0,
    "max_open_positions": 1,
    "max_open_positions_per_profile": 2,
    "max_portfolio_exposure_pct": 80.0,
    "leverage_multiplier": 6.0,
    "use_trend_invalidation_exit": True,
    "trend_invalidation_indicators": "exit",
    "min_position_age_for_trend_check": 5,
    "trading_hours": [],
    "trend_indicators": [
        {"type": "price_extended_above_ema", "params": {"ema": 50, "min_gap_pct": 2, "max_gap_pct": 10}},
        {"type": "rsi_range", "params": {"min": 70, "max": 100, "invert": False, "hard_stop": True}},
    ],
    "min_indicators_required": 2,
    "entry_indicator_groups": {'rsi_zone': {'hard_stop': True, 'require_all': False}, 'price_extension': {'hard_stop': True, 'require_all': False}},
    "entry_indicators": [
        {"type": "bollinger_bands", "params": {"band": "lower", "mode": "pct_b", "min_pct_b": 0.85}},
        {"type": "rsi_overbought_momentum", "params": {"lookback_candles": 5, "overbought_threshold": 68, "current_max": 70, "min_drop": 5, "drop_required": True, "require_sustained": True, "sustained_fall_mode": "net"}},
        {"type": "price_above_vwap", "params": {"min_gap_pct": 2, "max_gap_pct": 15}},
        {"type": "rsi_range", "params": {"min": 45, "max": 60, "invert": False}},
        {"type": "volume_spike", "params": {"min_ratio": 1.2, "max_ratio": 2.4}},
        {"type": "rsi_range", "params": {"min": 70, "max": 100, "invert": False}},
        {"type": "rsi_overbought", "params": {"side": "short", "max_value": 35, "hard_stop": True}},
    ],
    "min_entry_indicators_required": 4,
    "exit_indicators": [
        {"type": "price_extended_above_ema", "params": {"ema": 50, "min_gap_pct": 2, "max_gap_pct": 10}},
    ],
    "min_exit_indicators_required": 1,
},
# Exported from profile: default
{
    "display_name": "15m_tf_v3_rsizone_17tAI",
    "symbols": ['BNB_USDC', 'BTC_USDC', 'ETH_USDC', 'HYPE_USDC', 'SOL_USDC', 'XRP_USDC', 'ZEC_USDC'],
    "trading_type": "rules_live",
    "strategy_type": "trend_following",
    "market_type": "SPOT",
    "entry_timeframe": "15",
    "trend_timeframe": "60",
    "exit_timeframe": "15",
    "take_profit_pct": 0.8,
    "stop_loss_pct": 0.6,
    "trailing_stop_pct": 0.3,
    "arm_trailing_stop_pct": 0.4,
    "use_trailing_stop": True,
    "enable_signal_generation": True,
    "signal_cooldown_minutes": 20,
    "sl_cooldown_minutes": 125,
    "tp_cooldown_minutes": 65,
    "min_signal_confidence": 70.0,
    "min_volume_ratio": 1.0,
    "use_trend_filter": True,
    "use_entry_filter": True,
    "use_atr_filter": False,
    "max_position_hours": 18,
    "use_market_regime_filter": True,
    "regime_timeframe": "60",
    "default_order_size_usdc": 100.0,
    "max_position_size_pct": 40.0,
    "max_open_positions": 1,
    "max_open_positions_per_profile": 2,
    "max_portfolio_exposure_pct": 100.0,
    "leverage_multiplier": 1.0,
    "use_trend_invalidation_exit": True,
    "trend_invalidation_indicators": "exit",
    "min_position_age_for_trend_check": 15,
    "trading_hours": [
        {"day_of_week": 0, "start_time": "05:00", "end_time": "12:00", "enabled": True},
        {"day_of_week": 0, "start_time": "15:00", "end_time": "21:00", "enabled": True},
        {"day_of_week": 1, "start_time": "02:00", "end_time": "23:00", "enabled": True},
        {"day_of_week": 2, "start_time": "01:00", "end_time": "12:00", "enabled": True},
        {"day_of_week": 2, "start_time": "14:00", "end_time": "23:00", "enabled": True},
        {"day_of_week": 3, "start_time": "03:00", "end_time": "12:00", "enabled": True},
        {"day_of_week": 3, "start_time": "14:00", "end_time": "21:00", "enabled": True},
        {"day_of_week": 4, "start_time": "03:00", "end_time": "12:00", "enabled": True},
        {"day_of_week": 4, "start_time": "14:00", "end_time": "21:00", "enabled": True},
    ],
    "trend_indicators": [
        {"type": "ema_cross", "params": {}},
        {"type": "adx_regime", "params": {"min_adx": 22, "max_adx": 65, "hard_stop": True}},
        {"type": "rsi_overbought", "params": {"min_value": 60, "lookback_candles": 5, "hard_stop": True}},
    ],
    "min_indicators_required": 3,
    "entry_indicators": [
        {"type": "rsi_range", "params": {"min": 40, "max": 58, "invert": True}},
        {"type": "rsi_reversal_momentum", "params": {"lookback_candles": 6, "oversold_threshold": 45, "current_min": 44, "min_jump": 5, "require_sustained": True, "hard_stop": True}},
        {"type": "ema_slope", "params": {"ema": 20, "direction": "rising", "min_slope_pct": 0.01, "hard_stop": True}},
    ],
    "min_entry_indicators_required": 3,
    "exit_indicators": [
        {"type": "rsi_overbought", "params": {"min_value": 68, "hard_stop": True}},
        {"type": "ema_slope", "params": {"ema": 20, "direction": "rising", "min_slope_pct": -0.02, "hard_stop": True}},
        {"type": "rsi_threshold", "params": {"period": 14, "min_value": 44, "use_momentum": False}},
    ],
    "min_exit_indicators_required": 1,
},
# Exported from profile: short_trend_v16
{
    "display_name": "short_fade_v2c_bbwidthAI",
    "symbols": ['ETH_USDC', 'XRP_USDC', 'ZEC_USDC'],
    "trading_type": "rules_live",
    "strategy_type": "short_trend_following",
    "market_type": "PERP",
    "entry_timeframe": "15",
    "trend_timeframe": "60",
    "exit_timeframe": "60",
    "take_profit_pct": 1.2,
    "stop_loss_pct": 0.9,
    "trailing_stop_pct": 0.5,
    "arm_trailing_stop_pct": 0.6,
    "use_trailing_stop": True,
    "enable_signal_generation": True,
    "signal_cooldown_minutes": 20,
    "sl_cooldown_minutes": 65,
    "tp_cooldown_minutes": 65,
    "min_signal_confidence": 70.0,
    "min_volume_ratio": 1.0,
    "use_trend_filter": True,
    "use_entry_filter": True,
    "use_atr_filter": False,
    "max_position_hours": 5,
    "use_market_regime_filter": True,
    "regime_timeframe": "240",
    "default_order_size_usdc": 100.0,
    "max_position_size_pct": 40.0,
    "max_open_positions": 1,
    "max_open_positions_per_profile": 2,
    "max_portfolio_exposure_pct": 80.0,
    "leverage_multiplier": 5.0,
    "max_consecutive_stop_losses": 2,
    "consecutive_sl_lock_hours": 12,
    "use_trend_invalidation_exit": True,
    "trend_invalidation_indicators": "trend",
    "min_position_age_for_trend_check": 45,
    "trading_hours": [],
    "trend_indicators": [
        {"type": "ema_cross", "params": {"direction": "down", "hard_stop": True}},
        {"type": "adx_regime", "params": {"min_adx": 0, "max_adx": 32, "hard_stop": True}},
    ],
    "min_indicators_required": 2,
    "entry_indicators": [
        {"type": "volume_spike", "params": {"min_ratio": 0, "max_ratio": 0.6, "hard_stop": True}},
        {"type": "bollinger_bands", "params": {"band": "upper", "mode": "pct_b", "min_pct_b": 0.6, "max_pct_b": 1.2, "hard_stop": True}},
        {"type": "rsi_range", "params": {"min": 45, "max": 65, "invert": True, "hard_stop": True}},
        {"type": "bb_width_regime", "params": {"required_direction": "not_expanding", "lookback": 4}},
    ],
    "min_entry_indicators_required": 4,
},
# Exported from profile: spike_entry
{
    "display_name": "mr_opt_v7_adx_rsi_turn_wideAI",
    "symbols": ['BNB_USDC', 'BTC_USDC', 'ETH_USDC', 'SOL_USDC', 'XRP_USDC', 'ZEC_USDC'],
    "trading_type": "rules_live",
    "strategy_type": "mean_reversion",
    "market_type": "SPOT",
    "entry_timeframe": "15",
    "trend_timeframe": "60",
    "exit_timeframe": "60",
    "take_profit_pct": 2.2,
    "stop_loss_pct": 0.8,
    "trailing_stop_pct": 0.5,
    "arm_trailing_stop_pct": 1.2,
    "use_trailing_stop": True,
    "enable_signal_generation": True,
    "signal_cooldown_minutes": 18,
    "sl_cooldown_minutes": 15,
    "tp_cooldown_minutes": 15,
    "min_signal_confidence": 65.0,
    "min_volume_ratio": 1.0,
    "use_trend_filter": True,
    "use_entry_filter": True,
    "use_atr_filter": False,
    "max_position_hours": 6,
    "use_market_regime_filter": False,
    "regime_timeframe": None,
    "default_order_size_usdc": 200.0,
    "max_position_size_pct": 40.0,
    "max_open_positions": 1,
    "max_open_positions_per_profile": 2,
    "max_portfolio_exposure_pct": 80.0,
    "leverage_multiplier": 1.0,
    "use_trend_invalidation_exit": True,
    "trend_invalidation_indicators": "trend",
    "min_position_age_for_trend_check": 15,
    "trading_hours": [],
    "trend_indicators": [
        {"type": "rsi_oversold", "params": {"max_value": 38, "require_rising": True, "min_momentum": 0.3}},
        {"type": "adx_regime", "params": {"min_adx": 18, "max_adx": 65}},
    ],
    "min_indicators_required": 2,
    "entry_indicators": [
        {"type": "rsi_reversal_momentum", "params": {"lookback_candles": 8, "oversold_threshold": 30, "current_min": 30, "min_jump": 3, "require_sustained": False, "sustained_rise_mode": "net", "hard_stop": True}},
        {"type": "price_below_vwap", "params": {"min_gap_pct": -0.5, "max_gap_pct": -10}},
        {"type": "bollinger_bands", "params": {"band": "lower", "mode": "pct_b", "max_pct_b": 0.3}},
        {"type": "rsi_overbought", "params": {"min_value": 40}},
        {"type": "volume_spike", "params": {"min_ratio": 1, "max_ratio": 8}},
    ],
    "min_entry_indicators_required": 4,
},
]