profiles:
  default:
    enabled: true
    api_key_env: BACKPACK_API_KEY
    secret_env: SECRET
    take_profit_pct: 4
    stop_loss_pct: 5
    max_risk_pct: 0.25
    trailing_stop_pct: 5
    use_trailing_stop: true
    max_position_size: 25
    default_order_size_pct: 25

  15m_MB:
    enabled: false
    api_key_env: BP_API_KEY_15M
    secret_env: BP_SECRET_15M
    take_profit_pct: 1.2
    max_risk_pct: 0.25
    stop_loss_pct: 0.8
    trailing_stop_pct: 0.8
    use_trailing_stop: true
    max_position_size: 10
    max_risk_pct: 1.0
    default_order_size_pct: 20

  1hr_MB:
    enabled: false
    api_key_env: BP_API_KEY_1H
    secret_env: BP_SECRET_1H
    take_profit_pct: 2
    max_risk_pct: 0.25
    stop_loss_pct: 2.0
    trailing_stop_pct: 2.0
    use_trailing_stop: true
    max_position_size: 10
    max_risk_pct: 1.0
    default_order_size_pct: 20

  1m_MB:
    enabled: true
    api_key_env: BP_API_KEY_1M
    secret_env: BP_SECRET_1M
    take_profit_pct: 0.5
    max_risk_pct: 0.25
    stop_loss_pct: 0.4
    trailing_stop_pct: 0.5
    use_trailing_stop: false
    max_position_size: 10
    max_risk_pct: 1.0
    default_order_size_pct: 20

    